language: java

cache:
  directories:
  - $HOME/.m2

services:
- docker

notifications:
  email: false

jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...

before_install:
- npm install cesium
- mv node_modules/cesium/Build src/main/resources/static/Cesium

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
- docker build -t epoes/eqap .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push epoes/eqap

script:
- mvn test

